name: "zodgame"

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Run sign
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          python3 ./zodgame.py '${{ secrets.COOKIE }}' '${{ secrets.PUSH_TOKEN }}' '${{ secrets.PUSH_UID }}'
